version: '3.9'
services:
  edbox:
    container_name: edbox
    image: 'registry.richardx.win/edbox:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.edbox.rule=Host(`edbox.richardx.win`)

networks:
  default:
    name: proxy
    external: true
